### ISSUE TITLE
tmux ssh 

### ISSUE THREAD

**Issue by lanox** [pengwynn/dotfiles#17]
Hi

I stumbled across this https://github.com/pengwynn/dotfiles/blob/master/tmux/tmux.zsh and I was wondering how does that actually open new pane when ssh-ing to a remote server as per your comment ?

From what I can see it will rename the current pane but not open the new one..

**Comment by pengwynn** [comment]
> From what I can see it will rename the current pane but not open the new one..

Yup, you're right. That comment is incorrect. It only renames the pane to show the host. 

I think I used to have it hooked up to [another script](https://github.com/pengwynn/dotfiles/blob/master/bin/tmux-ssh-split) that did the split, but I'm not 100% sure without digging through history.
